# Yappari - настройки markdownlint
#
# Часть правил отключена, т.к. не соответствует стилю проекта.

default: true

# Длина строки - не ограничиваем
MD013: false

# Несколько заголовков H1 - разрешено в комментариях
MD025: false

# Смешивание markdown-расширений внутри одного блока - разрешено
MD044: false

# Пустые строки вокруг списков - необязательно
MD032: false

# Код внутри отступов - разрешен
MD046: false

# HTML-код - разрешен
MD033: false

# так как есть HTML-header начинать с h1 - не ограничиваем
MD041: false
